export const IpcChannels = {
  PROXY_START: 'proxy:start',
  PROXY_STOP: 'proxy:stop',
  PROXY_GET_STATUS: 'proxy:getStatus',
  PROXY_STATUS_CHANGED: 'proxy:statusChanged',
  PROXY_GET_STATISTICS: 'proxy:getStatistics',
  PROXY_RESET_STATISTICS: 'proxy:resetStatistics',

  CONFIG_GET: 'config:get',
  CONFIG_UPDATE: 'config:update',
  CONFIG_CHANGED: 'config:changed',

  STORE_GET: 'store:get',
  STORE_SET: 'store:set',
  STORE_DELETE: 'store:delete',
  STORE_CLEAR_ALL: 'store:clearAll',
  STORE_INIT_ERROR: 'store:initError',
  STORE_RETRY_INIT: 'store:retryInit',

  PROVIDERS_GET_ALL: 'providers:getAll',
  PROVIDERS_GET_BUILTIN: 'providers:getBuiltin',
  PROVIDERS_ADD: 'providers:add',
  PROVIDERS_UPDATE: 'providers:update',
  PROVIDERS_DELETE: 'providers:delete',
  PROVIDERS_CHECK_STATUS: 'providers:checkStatus',
  PROVIDERS_CHECK_ALL_STATUS: 'providers:checkAllStatus',
  PROVIDERS_DUPLICATE: 'providers:duplicate',
  PROVIDERS_EXPORT: 'providers:export',
  PROVIDERS_IMPORT: 'providers:import',
  PROVIDERS_SYNC_MODELS: 'providers:syncModels',
  PROVIDERS_UPDATE_MODELS: 'providers:updateModels',
  PROVIDERS_GET_EFFECTIVE_MODELS: 'providers:getEffectiveModels',
  PROVIDERS_ADD_CUSTOM_MODEL: 'providers:addCustomModel',
  PROVIDERS_REMOVE_MODEL: 'providers:removeModel',
  PROVIDERS_RESET_MODELS: 'providers:resetModels',

  ACCOUNTS_GET_ALL: 'accounts:getAll',
  ACCOUNTS_GET_BY_ID: 'accounts:getById',
  ACCOUNTS_GET_BY_PROVIDER: 'accounts:getByProvider',
  ACCOUNTS_ADD: 'accounts:add',
  ACCOUNTS_UPDATE: 'accounts:update',
  ACCOUNTS_DELETE: 'accounts:delete',
  ACCOUNTS_VALIDATE: 'accounts:validate',
  ACCOUNTS_VALIDATE_TOKEN: 'accounts:validateToken',
  ACCOUNTS_GET_CREDITS: 'accounts:getCredits',
  ACCOUNTS_CLEAR_CHATS: 'accounts:clearChats',

  OAUTH_START_LOGIN: 'oauth:startLogin',
  OAUTH_CANCEL_LOGIN: 'oauth:cancelLogin',
  OAUTH_CALLBACK: 'oauth:callback',
  OAUTH_LOGIN_WITH_TOKEN: 'oauth:loginWithToken',
  OAUTH_VALIDATE_TOKEN: 'oauth:validateToken',
  OAUTH_REFRESH_TOKEN: 'oauth:refreshToken',
  OAUTH_GET_STATUS: 'oauth:getStatus',
  OAUTH_PROGRESS: 'oauth:progress',
  OAUTH_START_IN_APP_LOGIN: 'oauth:startInAppLogin',
  OAUTH_CANCEL_IN_APP_LOGIN: 'oauth:cancelInAppLogin',
  OAUTH_IN_APP_LOGIN_STATUS: 'oauth:inAppLoginStatus',

  LOGS_GET: 'logs:get',
  LOGS_GET_STATS: 'logs:getStats',
  LOGS_GET_TREND: 'logs:getTrend',
  LOGS_GET_ACCOUNT_TREND: 'logs:getAccountTrend',
  LOGS_CLEAR: 'logs:clear',
  LOGS_EXPORT: 'logs:export',
  LOGS_GET_BY_ID: 'logs:getById',
  LOGS_NEW_LOG: 'logs:newLog',

  REQUEST_LOGS_GET: 'requestLogs:get',
  REQUEST_LOGS_GET_BY_ID: 'requestLogs:getById',
  REQUEST_LOGS_GET_STATS: 'requestLogs:getStats',
  REQUEST_LOGS_GET_TREND: 'requestLogs:getTrend',
  REQUEST_LOGS_CLEAR: 'requestLogs:clear',
  REQUEST_LOGS_NEW: 'requestLogs:new',

  STATISTICS_GET: 'statistics:get',
  STATISTICS_GET_TODAY: 'statistics:getToday',

  APP_GET_VERSION: 'app:getVersion',
  APP_CHECK_UPDATE: 'app:checkUpdate',
  APP_DOWNLOAD_UPDATE: 'app:downloadUpdate',
  APP_INSTALL_UPDATE: 'app:installUpdate',
  APP_UPDATE_CHECKING: 'app:updateChecking',
  APP_UPDATE_AVAILABLE: 'app:updateAvailable',
  APP_UPDATE_NOT_AVAILABLE: 'app:updateNotAvailable',
  APP_UPDATE_PROGRESS: 'app:updateProgress',
  APP_UPDATE_DOWNLOADED: 'app:updateDownloaded',
  APP_UPDATE_ERROR: 'app:updateError',
  APP_GET_UPDATE_STATUS: 'app:getUpdateStatus',
  APP_MINIMIZE: 'app:minimize',
  APP_MAXIMIZE: 'app:maximize',
  APP_CLOSE: 'app:close',
  APP_SHOW_WINDOW: 'app:showWindow',
  APP_HIDE_WINDOW: 'app:hideWindow',
  APP_OPEN_EXTERNAL: 'app:openExternal',

  PROMPTS_GET_ALL: 'prompts:getAll',
  PROMPTS_GET_BUILTIN: 'prompts:getBuiltin',
  PROMPTS_GET_CUSTOM: 'prompts:getCustom',
  PROMPTS_GET_BY_ID: 'prompts:getById',
  PROMPTS_ADD: 'prompts:add',
  PROMPTS_UPDATE: 'prompts:update',
  PROMPTS_DELETE: 'prompts:delete',
  PROMPTS_GET_BY_TYPE: 'prompts:getByType',

  SESSION_GET_CONFIG: 'session:getConfig',
  SESSION_UPDATE_CONFIG: 'session:updateConfig',
  SESSION_GET_ALL: 'session:getAll',
  SESSION_GET_ACTIVE: 'session:getActive',
  SESSION_GET_BY_ID: 'session:getById',
  SESSION_GET_BY_ACCOUNT: 'session:getByAccount',
  SESSION_GET_BY_PROVIDER: 'session:getByProvider',
  SESSION_DELETE: 'session:delete',
  SESSION_CLEAR_ALL: 'session:clearAll',
  SESSION_CLEAN_EXPIRED: 'session:cleanExpired',

  MANAGEMENT_API_GET_CONFIG: 'managementApi:getConfig',
  MANAGEMENT_API_UPDATE_CONFIG: 'managementApi:updateConfig',
  MANAGEMENT_API_GENERATE_SECRET: 'managementApi:generateSecret',

  CONTEXT_MANAGEMENT_GET_CONFIG: 'contextManagement:getConfig',
  CONTEXT_MANAGEMENT_UPDATE_CONFIG: 'contextManagement:updateConfig',
} as const

export type IpcChannel = (typeof IpcChannels)[keyof typeof IpcChannels]
